export const SwrKey = {
  cart_list: 'cart_list',
  cart_count: 'cart_count',
  cart_company_promotion: (id: number) => `cart_company_promotion_${id}`,
  order_drafts: 'order_drafts',
  orders: 'orders',
  home_categories: 'home_categories',
  productsBarcode: 'productsBarcode',
  get_promotions: 'get_promotions',
  categories: 'categories',
  newest_products: 'newest_products',
  promotions: ({ sale_order_id, customer_id }: { sale_order_id: number; customer_id: number }) =>
    `promotions-${sale_order_id}-${customer_id}`,
  globalPromotions: 'global_promotions',
  promotionsApplyOnOrder: (companyId: number) => `promotions_apply_on_order_${companyId}`,
  promotionsApplyOnProduct: (productId: number) => `promotions_apply_on_product_${productId}`,
  promotionsApplyOnCategory: (categoryId: number) => `promotions_apply_on_category_${categoryId}`,
  cartSummary: `cart_summary`,
  // cartSummaryLoading: `cart_summary_loading`,
  userInfo: 'userInfo',
  orderHistoryList: 'order_history_list',
  orderHistoryDetail: (id: number) => `order_history_detail_${id}`,
  shareOrderFile: (id: number) => `share_order_file_${id}`,
  getOrderStatus: 'get_order_satus',
  get_customers: 'get_customers',
  get_report: 'get_report',
  get_report_user: (id: number) => `get_report_${id}`,
  home_category: 'home_category',
  accounts: 'accounts',
  products: 'products',
  fitler_products: 'fitler_products',
  home_banners: 'home_banners',
  products_deal: 'products_deal',
  best_sell_products: 'best_sell_products',
  today_route: 'today_route',
  visit_history: 'visit_history',
  routes: 'routes',
  rating_tags: (type: string) => `rating_tags_${type}`,
  account_info: (id: number) => `account_info_${id}`,
  attendance_images: (id: number) => `attendance_images_${id}`,
  // rating_photos: (type: RatingType, id: number) => `rating_photos_${type}_${id}`,
  rating_data: (id: number) => `rating_data_${id}`,
  inventories: (id: number) => `inventories_${id}`,
  select_address: (id: number) => `select_address_${id}`,
  route_detail: (id: number) => `route_detail_${id}`,
  detail_routes: (id: number) => `detail_routes_${id}`,
  companies: 'companies',
  get_delivery: (id: number) => `get_delivery_${id}`,
  route_customers: (id: number) => `route_customers_${id}`,
  inventory_products: 'inventory_products',
  child_categories: (id: number) => `child_categories_${id}`,
  filter_categories: 'filter_categories',
  notifications: 'notifications',
  notification_count: 'notification_count',
  debts: 'debts',
  debts_filter: 'debts_filter',
  debt_detail: (id: number) => `debt_detail_${id}`,
  customerDebts: (id: number) => `customer_debts_${id}`,
  order_return_deliveries: (id: number) => `order_return_deliveries_${id}`,
  order_return_products: 'order_return_products',
  order_returns: 'order_returns',
  order_return_reasons: 'order_return_reasons',
  wishlist: 'wishlist',
  attribute_minors: `attribute_minors`,
  category_minors: 'category_minors',
  category_majors: 'category_majors',
  // product_detail: (type: GetProductType, id: number) => `product_detail_${type}_${id}`,
  products_related: 'products_related',
  product_comment: (id: number) => `product_comment_${id}`,
  deal_detail: (id: number) => `deal_detail_${id}`,
  conversations: 'conversations',
  conversation: (id: string) => `conversation_${id}`,
  messages_in_conversation: (id: string) => `messages_${id}`,
  search_conversation: 'search_conversation',
  uom_categories: 'uom_categories',
  select_uom_category: 'select_uom_category',
  uom_category: (id: number) => `uom_category_${id}`,
  uomList: (id: number) => `uoms_${id}`,
  attributes: 'attributes',
  attribute: (id: number) => `attribute_${id}`,
  attribute_values: (id: number) => `attribute_values_${id}`,
  attribute_minor_list: 'attribute_minor_list',
  attribute_minor_values: (id: number) => `attribute_minor_values_${id}`,
  attribute_minor: (id: number) => `attribute_minor_${id}`,
  listSaleOff: (cId: number) => `list_sale_off_${cId}`,
  home_news: 'home_news',
  news_screen: 'news_screen',
  get_payment_method: 'get_payment_method',
}
