import { StyleSheet } from 'react-native'
import { Colors } from './color'

export const Typography = StyleSheet.create({
  body18Bold: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Inter-Bold',
    fontWeight: '700',
    color: Colors.text,
  },
  body18SemiBold: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    color: Colors.text,
  },
  body18Medium: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: Colors.text,
  },
  body18Normal: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Inter-Regular',
    color: Colors.text,
  },
  body16Bold: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Inter-Bold',
    fontWeight: '700',
    color: Colors.text,
  },
  body16SemiBold: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    color: Colors.text,
  },
  body16Medium: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Inter-Medium',
    color: Colors.text,
    fontWeight: '500',
  },
  body16Normal: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Inter-Regular',
    color: Colors.text,
    fontWeight: '400',
  },
  body15Bold: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Inter-Bold',
    color: Colors.text,
    fontWeight: '700',
  },
  body15SemiBold: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Inter-SemiBold',
    color: Colors.text,
    fontWeight: '600',
  },
  body15Medium: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Inter-Medium',
    color: Colors.text,
  },
  body15Normal: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Inter-Regular',
    color: Colors.text,
  },
  body14Bold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Inter-Bold',
    color: Colors.text,
    fontWeight: '700',
  },
  body14ExtraBold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Inter-ExtraBold',
    color: Colors.text,
    fontWeight: '700',
  },
  body14SemiBold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Inter-SemiBold',
    color: Colors.text,
    fontWeight: '600',
  },
  body14Medium: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Inter-Medium',
    color: Colors.text,
  },
  body14Normal: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Inter-Regular',
    color: Colors.text,
  },
  body13Bold: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter-Bold',
    color: Colors.text,
    fontWeight: '700',
  },
  body13SemiBold: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter-SemiBold',
    color: Colors.text,
    fontWeight: '600',
  },
  body13Medium: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter-Medium',
    color: Colors.text,
  },
  body13Normal: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter-Regular',
    color: Colors.text,
  },
  body12Bold: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Inter-Bold',
    color: Colors.text,
  },
  body12SemiBold: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Inter-SemiBold',
    color: Colors.text,
    fontWeight: '600',
  },
  body12Medium: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Inter-Medium',
    color: Colors.text,
  },
  body12Normal: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    color: Colors.text,
  },
  body10Bold: {
    fontSize: 10,
    lineHeight: 14,
    fontFamily: 'Inter-Bold',
    color: Colors.text,
  },
  body10SemiBold: {
    fontSize: 10,
    lineHeight: 14,
    fontFamily: 'Inter-SemiBold',
    color: Colors.text,
  },
  body10Medium: {
    fontSize: 10,
    lineHeight: 14,
    fontFamily: 'Inter-Medium',
    color: Colors.text,
  },
  body10Normal: {
    fontSize: 10,
    lineHeight: 14,
    fontFamily: 'Inter-Regular',
    color: Colors.text,
  },
})
